### ISSUE TITLE
Incompatible with Astral Sorcery

### ISSUE THREAD

**Issue by brisingraerowing** [Meldexun/ReachFix#7] opened 2023-01-19 16:26 UTC
**Describe the bug**
Crash on startup when installed with Astral Sorcery

**To Reproduce**
1. Install with Astral Sorcery
2. Launch Game
3. Crash

**Screenshots/Videos**
N/A

**Versions**
Reach Fix: 1.0.8
Forge: 14.23.5.2860
Minecraft: 1,12,2
Other mods (necessary to reproduce the bug): Astral Sorcery - 1.10.27

**Log File**
[Game Log](https://gist.github.com/brisingraerowing/b77a95c03205ccbdb1b25869e3b28d60)

**Comment by Meldexun** [comment] 2023-01-23 02:35
I can't really fix this issue on my end. Have you tried reporting this to Astral Sorcery?

**Comment by ukmojb** [comment] 2023-03-04 01:52
> I can't really fix this issue on my end. Have you tried reporting this to Astral Sorcery?

But Astral Sorcery of 1.12 version has been out of play for a long time, so can you fix this? 
This is important, thanks! 
My native language is not English, may be a bit wrong, sorry.

**Comment by EverSoul** [comment] 2023-03-05 17:18
Can confirm this is happening. Switching to an older version of reach fix solves the issue.

**Comment by hoolatehip** [comment] 2023-03-29 20:39
I have this problem. It occurs every time I try to launch after updating Reach Fix from 1.0.5 to 1.0.8. 
Edit: Downgrading solved it. The problem does **not** occur on 1.0.6. 

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  Botania Tweaks Core (botaniatweaks-1.9.1.jar)
  NothiriumPlugin (Nothirium-1.12.2-0.1.4-beta.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
  ReachFixPlugin (ReachFix-1.12.2-1.0.8.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.29.4_Forge_1.12.jar)
  ReplantFMLLoadingPlugin (replant1.12.2-1.0.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  RenderLibPlugin (RenderLib-1.12.2-1.0.8.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  FutureMC (future-mc-0.2.11.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  UniDictCoreMod (UniDict-1.12.2-3.0.10.jar)
  XaeroMinimapPlugin (Xaeros_Minimap_23.3.2_Forge_1.12.jar)
  CharmLoadingPlugin (Charm-1.12.2-1.4.1.jar)
  Plugin (NotEnoughIDs-1.5.4.4.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  ShetiPhian-ASM (ShetiPhian-ASM-1.12.0.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  LoadingPlugin (HardcoreDarkness-MC1.12.2-2.0.jar)
  EntityCullingPlugin (EntityCulling-1.12.2-6.0.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 3/29/23 3:33 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/EntityRenderer
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 36 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.EntityRenderer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 43 more
Caused by: hellfirepvp.astralsorcery.core.ASMTransformationException: Applying ClassPatches failed (ClassName: buq - net.minecraft.client.renderer.EntityRenderer) - Rethrowing exception!
	at hellfirepvp.astralsorcery.core.transform.AstralPatchTransformer.transformClassNode(AstralPatchTransformer.java:126)
	at hellfirepvp.astralsorcery.core.AstralTransformer.transform(AstralTransformer.java:60)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: hellfirepvp.astralsorcery.core.ASMTransformationException: Failed to applyServer ASM Transformation ClassPatch PATCHENTITYRENDEREREXTENDEDENTITYREACH
	at hellfirepvp.astralsorcery.core.ClassPatch.transform(ClassPatch.java:38)
	at hellfirepvp.astralsorcery.core.transform.AstralPatchTransformer.transformClassNode(AstralPatchTransformer.java:121)
	... 48 more
Caused by: hellfirepvp.astralsorcery.core.ASMTransformationException: Couldn't find method Instruction: owner=net/minecraft/client/multiplayer/PlayerControllerMP nameDeobf=extendedReach nameObf=func_78749_i signature=()Z
	at hellfirepvp.astralsorcery.core.ClassPatch.getFirstMethodCallAfter(ClassPatch.java:149)
	at hellfirepvp.astralsorcery.core.ClassPatch.getNthMethodCallAfter(ClassPatch.java:191)
	at hellfirepvp.astralsorcery.core.ClassPatch.getFirstMethodCall(ClassPatch.java:181)
	at hellfirepvp.astralsorcery.core.patch.helper.PatchEntityRendererExtendedEntityReach.patch(PatchEntityRendererExtendedEntityReach.java:32)
	at hellfirepvp.astralsorcery.core.ClassPatch.transform(ClassPatch.java:36)
	... 49 more

**Comment by Meldexun** [comment] 2023-07-09 14:07
Fixed in 1.12.2-1.0.9

**Closed as completed by Meldexun** 2023-07-09 14:07 UTC
Labels: bug
